pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK21'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Clean & Build') {
            steps {
                dir('order-batch-processing-main') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('order-batch-processing-main') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('order-batch-processing-main') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful ✅'
        }
        failure {
            echo 'Build Failed ❌'
        }
    }
}
